/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL.impl;

import eu.extremexp.ssfhai.dsl.mLDSL.FLOAT;
import eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FLOAT</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.FLOATImpl#getDec <em>Dec</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.FLOATImpl#getPer <em>Per</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FLOATImpl extends MinimalEObjectImpl.Container implements FLOAT
{
  /**
   * The default value of the '{@link #getDec() <em>Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDec()
   * @generated
   * @ordered
   */
  protected static final int DEC_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDec() <em>Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDec()
   * @generated
   * @ordered
   */
  protected int dec = DEC_EDEFAULT;

  /**
   * The default value of the '{@link #getPer() <em>Per</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPer()
   * @generated
   * @ordered
   */
  protected static final int PER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPer() <em>Per</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPer()
   * @generated
   * @ordered
   */
  protected int per = PER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FLOATImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MLDSLPackage.Literals.FLOAT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDec()
  {
    return dec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDec(int newDec)
  {
    int oldDec = dec;
    dec = newDec;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLDSLPackage.FLOAT__DEC, oldDec, dec));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPer()
  {
    return per;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPer(int newPer)
  {
    int oldPer = per;
    per = newPer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLDSLPackage.FLOAT__PER, oldPer, per));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MLDSLPackage.FLOAT__DEC:
        return getDec();
      case MLDSLPackage.FLOAT__PER:
        return getPer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MLDSLPackage.FLOAT__DEC:
        setDec((Integer)newValue);
        return;
      case MLDSLPackage.FLOAT__PER:
        setPer((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MLDSLPackage.FLOAT__DEC:
        setDec(DEC_EDEFAULT);
        return;
      case MLDSLPackage.FLOAT__PER:
        setPer(PER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MLDSLPackage.FLOAT__DEC:
        return dec != DEC_EDEFAULT;
      case MLDSLPackage.FLOAT__PER:
        return per != PER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (dec: ");
    result.append(dec);
    result.append(", per: ");
    result.append(per);
    result.append(')');
    return result.toString();
  }

} //FLOATImpl
