/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL.impl;

import eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage;
import eu.extremexp.ssfhai.dsl.mLDSL.Param;
import eu.extremexp.ssfhai.dsl.mLDSL.ParamValue;
import eu.extremexp.ssfhai.dsl.mLDSL.WorkflowEntinty;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamImpl#getName <em>Name</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamImpl#getParamValue <em>Param Value</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamImpl#getEntityValue <em>Entity Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParamImpl extends MinimalEObjectImpl.Container implements Param
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParamValue() <em>Param Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParamValue()
   * @generated
   * @ordered
   */
  protected ParamValue paramValue;

  /**
   * The cached value of the '{@link #getEntityValue() <em>Entity Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityValue()
   * @generated
   * @ordered
   */
  protected WorkflowEntinty entityValue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParamImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MLDSLPackage.Literals.PARAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLDSLPackage.PARAM__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ParamValue getParamValue()
  {
    return paramValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParamValue(ParamValue newParamValue, NotificationChain msgs)
  {
    ParamValue oldParamValue = paramValue;
    paramValue = newParamValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MLDSLPackage.PARAM__PARAM_VALUE, oldParamValue, newParamValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParamValue(ParamValue newParamValue)
  {
    if (newParamValue != paramValue)
    {
      NotificationChain msgs = null;
      if (paramValue != null)
        msgs = ((InternalEObject)paramValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MLDSLPackage.PARAM__PARAM_VALUE, null, msgs);
      if (newParamValue != null)
        msgs = ((InternalEObject)newParamValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MLDSLPackage.PARAM__PARAM_VALUE, null, msgs);
      msgs = basicSetParamValue(newParamValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLDSLPackage.PARAM__PARAM_VALUE, newParamValue, newParamValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkflowEntinty getEntityValue()
  {
    if (entityValue != null && entityValue.eIsProxy())
    {
      InternalEObject oldEntityValue = (InternalEObject)entityValue;
      entityValue = (WorkflowEntinty)eResolveProxy(oldEntityValue);
      if (entityValue != oldEntityValue)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MLDSLPackage.PARAM__ENTITY_VALUE, oldEntityValue, entityValue));
      }
    }
    return entityValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkflowEntinty basicGetEntityValue()
  {
    return entityValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntityValue(WorkflowEntinty newEntityValue)
  {
    WorkflowEntinty oldEntityValue = entityValue;
    entityValue = newEntityValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLDSLPackage.PARAM__ENTITY_VALUE, oldEntityValue, entityValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MLDSLPackage.PARAM__PARAM_VALUE:
        return basicSetParamValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MLDSLPackage.PARAM__NAME:
        return getName();
      case MLDSLPackage.PARAM__PARAM_VALUE:
        return getParamValue();
      case MLDSLPackage.PARAM__ENTITY_VALUE:
        if (resolve) return getEntityValue();
        return basicGetEntityValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MLDSLPackage.PARAM__NAME:
        setName((String)newValue);
        return;
      case MLDSLPackage.PARAM__PARAM_VALUE:
        setParamValue((ParamValue)newValue);
        return;
      case MLDSLPackage.PARAM__ENTITY_VALUE:
        setEntityValue((WorkflowEntinty)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MLDSLPackage.PARAM__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MLDSLPackage.PARAM__PARAM_VALUE:
        setParamValue((ParamValue)null);
        return;
      case MLDSLPackage.PARAM__ENTITY_VALUE:
        setEntityValue((WorkflowEntinty)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MLDSLPackage.PARAM__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MLDSLPackage.PARAM__PARAM_VALUE:
        return paramValue != null;
      case MLDSLPackage.PARAM__ENTITY_VALUE:
        return entityValue != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ParamImpl
