/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL.impl;

import eu.extremexp.ssfhai.dsl.mLDSL.Data;
import eu.extremexp.ssfhai.dsl.mLDSL.Flow;
import eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage;
import eu.extremexp.ssfhai.dsl.mLDSL.Network;
import eu.extremexp.ssfhai.dsl.mLDSL.Task;
import eu.extremexp.ssfhai.dsl.mLDSL.Workflow;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl#getName <em>Name</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl#getTasks <em>Tasks</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl#getFlows <em>Flows</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl#getData <em>Data</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl#getNetworks <em>Networks</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkflowImpl extends MinimalEObjectImpl.Container implements Workflow
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTasks() <em>Tasks</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTasks()
   * @generated
   * @ordered
   */
  protected EList<Task> tasks;

  /**
   * The cached value of the '{@link #getFlows() <em>Flows</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFlows()
   * @generated
   * @ordered
   */
  protected EList<Flow> flows;

  /**
   * The cached value of the '{@link #getData() <em>Data</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getData()
   * @generated
   * @ordered
   */
  protected EList<Data> data;

  /**
   * The cached value of the '{@link #getNetworks() <em>Networks</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNetworks()
   * @generated
   * @ordered
   */
  protected EList<Network> networks;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkflowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MLDSLPackage.Literals.WORKFLOW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLDSLPackage.WORKFLOW__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Task> getTasks()
  {
    if (tasks == null)
    {
      tasks = new EObjectContainmentEList<Task>(Task.class, this, MLDSLPackage.WORKFLOW__TASKS);
    }
    return tasks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Flow> getFlows()
  {
    if (flows == null)
    {
      flows = new EObjectContainmentEList<Flow>(Flow.class, this, MLDSLPackage.WORKFLOW__FLOWS);
    }
    return flows;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Data> getData()
  {
    if (data == null)
    {
      data = new EObjectContainmentEList<Data>(Data.class, this, MLDSLPackage.WORKFLOW__DATA);
    }
    return data;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Network> getNetworks()
  {
    if (networks == null)
    {
      networks = new EObjectContainmentEList<Network>(Network.class, this, MLDSLPackage.WORKFLOW__NETWORKS);
    }
    return networks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MLDSLPackage.WORKFLOW__TASKS:
        return ((InternalEList<?>)getTasks()).basicRemove(otherEnd, msgs);
      case MLDSLPackage.WORKFLOW__FLOWS:
        return ((InternalEList<?>)getFlows()).basicRemove(otherEnd, msgs);
      case MLDSLPackage.WORKFLOW__DATA:
        return ((InternalEList<?>)getData()).basicRemove(otherEnd, msgs);
      case MLDSLPackage.WORKFLOW__NETWORKS:
        return ((InternalEList<?>)getNetworks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MLDSLPackage.WORKFLOW__NAME:
        return getName();
      case MLDSLPackage.WORKFLOW__TASKS:
        return getTasks();
      case MLDSLPackage.WORKFLOW__FLOWS:
        return getFlows();
      case MLDSLPackage.WORKFLOW__DATA:
        return getData();
      case MLDSLPackage.WORKFLOW__NETWORKS:
        return getNetworks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MLDSLPackage.WORKFLOW__NAME:
        setName((String)newValue);
        return;
      case MLDSLPackage.WORKFLOW__TASKS:
        getTasks().clear();
        getTasks().addAll((Collection<? extends Task>)newValue);
        return;
      case MLDSLPackage.WORKFLOW__FLOWS:
        getFlows().clear();
        getFlows().addAll((Collection<? extends Flow>)newValue);
        return;
      case MLDSLPackage.WORKFLOW__DATA:
        getData().clear();
        getData().addAll((Collection<? extends Data>)newValue);
        return;
      case MLDSLPackage.WORKFLOW__NETWORKS:
        getNetworks().clear();
        getNetworks().addAll((Collection<? extends Network>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MLDSLPackage.WORKFLOW__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MLDSLPackage.WORKFLOW__TASKS:
        getTasks().clear();
        return;
      case MLDSLPackage.WORKFLOW__FLOWS:
        getFlows().clear();
        return;
      case MLDSLPackage.WORKFLOW__DATA:
        getData().clear();
        return;
      case MLDSLPackage.WORKFLOW__NETWORKS:
        getNetworks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MLDSLPackage.WORKFLOW__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MLDSLPackage.WORKFLOW__TASKS:
        return tasks != null && !tasks.isEmpty();
      case MLDSLPackage.WORKFLOW__FLOWS:
        return flows != null && !flows.isEmpty();
      case MLDSLPackage.WORKFLOW__DATA:
        return data != null && !data.isEmpty();
      case MLDSLPackage.WORKFLOW__NETWORKS:
        return networks != null && !networks.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //WorkflowImpl
