/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MLDSLIdeModule extends AbstractMLDSLIdeModule {
}
