/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.extremexp.ssfhai.dsl.MLDSLRuntimeModule;
import eu.extremexp.ssfhai.dsl.MLDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MLDSLIdeSetup extends MLDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MLDSLRuntimeModule _mLDSLRuntimeModule = new MLDSLRuntimeModule();
    MLDSLIdeModule _mLDSLIdeModule = new MLDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mLDSLRuntimeModule, _mLDSLIdeModule));
  }
}
