/*
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.parser.antlr;

import com.google.inject.Inject;
import eu.extremexp.ssfhai.dsl.parser.antlr.internal.InternalMLDSLParser;
import eu.extremexp.ssfhai.dsl.services.MLDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MLDSLParser extends AbstractAntlrParser {

	@Inject
	private MLDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMLDSLParser createParser(XtextTokenStream stream) {
		return new InternalMLDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MLDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MLDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
