/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getPath <em>Path</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getFeatures <em>Features</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getData()
 * @model
 * @generated
 */
public interface Data extends WorkflowEntinty
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getData_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' attribute.
   * @see #setFeatures(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getData_Features()
   * @model
   * @generated
   */
  String getFeatures();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getFeatures <em>Features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Features</em>' attribute.
   * @see #getFeatures()
   * @generated
   */
  void setFeatures(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getData_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

} // Data
