/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FLOAT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getDec <em>Dec</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getPer <em>Per</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getFLOAT()
 * @model
 * @generated
 */
public interface FLOAT extends EObject
{
  /**
   * Returns the value of the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec</em>' attribute.
   * @see #setDec(int)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getFLOAT_Dec()
   * @model
   * @generated
   */
  int getDec();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getDec <em>Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec</em>' attribute.
   * @see #getDec()
   * @generated
   */
  void setDec(int value);

  /**
   * Returns the value of the '<em><b>Per</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Per</em>' attribute.
   * @see #setPer(int)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getFLOAT_Per()
   * @model
   * @generated
   */
  int getPer();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getPer <em>Per</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Per</em>' attribute.
   * @see #getPer()
   * @generated
   */
  void setPer(int value);

} // FLOAT
