/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Forward</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Forward#getSequenceStart <em>Sequence Start</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Forward#getSequence <em>Sequence</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getForward()
 * @model
 * @generated
 */
public interface Forward extends EObject
{
  /**
   * Returns the value of the '<em><b>Sequence Start</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequence Start</em>' reference.
   * @see #setSequenceStart(Layer)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getForward_SequenceStart()
   * @model
   * @generated
   */
  Layer getSequenceStart();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Forward#getSequenceStart <em>Sequence Start</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sequence Start</em>' reference.
   * @see #getSequenceStart()
   * @generated
   */
  void setSequenceStart(Layer value);

  /**
   * Returns the value of the '<em><b>Sequence</b></em>' reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Layer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequence</em>' reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getForward_Sequence()
   * @model
   * @generated
   */
  EList<Layer> getSequence();

} // Forward
