/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Layer Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getLayerType()
 * @model
 * @generated
 */
public enum LayerType implements Enumerator
{
  /**
   * The '<em><b>Input</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPUT_VALUE
   * @generated
   * @ordered
   */
  INPUT(0, "Input", "Input"),

  /**
   * The '<em><b>Linear</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINEAR_VALUE
   * @generated
   * @ordered
   */
  LINEAR(1, "Linear", "Linear"),

  /**
   * The '<em><b>Sigmoid</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIGMOID_VALUE
   * @generated
   * @ordered
   */
  SIGMOID(2, "Sigmoid", "Sigmoid"),

  /**
   * The '<em><b>BN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BN_VALUE
   * @generated
   * @ordered
   */
  BN(3, "BN", "BN"),

  /**
   * The '<em><b>Drop Out</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DROP_OUT_VALUE
   * @generated
   * @ordered
   */
  DROP_OUT(4, "DropOut", "DropOut");

  /**
   * The '<em><b>Input</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPUT
   * @model name="Input"
   * @generated
   * @ordered
   */
  public static final int INPUT_VALUE = 0;

  /**
   * The '<em><b>Linear</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINEAR
   * @model name="Linear"
   * @generated
   * @ordered
   */
  public static final int LINEAR_VALUE = 1;

  /**
   * The '<em><b>Sigmoid</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIGMOID
   * @model name="Sigmoid"
   * @generated
   * @ordered
   */
  public static final int SIGMOID_VALUE = 2;

  /**
   * The '<em><b>BN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BN
   * @model
   * @generated
   * @ordered
   */
  public static final int BN_VALUE = 3;

  /**
   * The '<em><b>Drop Out</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DROP_OUT
   * @model name="DropOut"
   * @generated
   * @ordered
   */
  public static final int DROP_OUT_VALUE = 4;

  /**
   * An array of all the '<em><b>Layer Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final LayerType[] VALUES_ARRAY =
    new LayerType[]
    {
      INPUT,
      LINEAR,
      SIGMOID,
      BN,
      DROP_OUT,
    };

  /**
   * A public read-only list of all the '<em><b>Layer Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<LayerType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Layer Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static LayerType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      LayerType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Layer Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static LayerType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      LayerType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Layer Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static LayerType get(int value)
  {
    switch (value)
    {
      case INPUT_VALUE: return INPUT;
      case LINEAR_VALUE: return LINEAR;
      case SIGMOID_VALUE: return SIGMOID;
      case BN_VALUE: return BN;
      case DROP_OUT_VALUE: return DROP_OUT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private LayerType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //LayerType
