/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLFactory
 * @model kind="package"
 * @generated
 */
public interface MLDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mLDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.extremexp.eu/ssfhai/dsl/MLDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mLDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MLDSLPackage eINSTANCE = eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ModelImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Workflows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WORKFLOWS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl <em>Workflow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getWorkflow()
   * @generated
   */
  int WORKFLOW = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__NAME = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__TASKS = 1;

  /**
   * The feature id for the '<em><b>Flows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__FLOWS = 2;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__DATA = 3;

  /**
   * The feature id for the '<em><b>Networks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__NETWORKS = 4;

  /**
   * The number of structural features of the '<em>Workflow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowEntintyImpl <em>Workflow Entinty</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowEntintyImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getWorkflowEntinty()
   * @generated
   */
  int WORKFLOW_ENTINTY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW_ENTINTY__NAME = 0;

  /**
   * The number of structural features of the '<em>Workflow Entinty</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW_ENTINTY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.DataImpl <em>Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.DataImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getData()
   * @generated
   */
  int DATA = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__NAME = WORKFLOW_ENTINTY__NAME;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__PATH = WORKFLOW_ENTINTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__FEATURES = WORKFLOW_ENTINTY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__TARGET = WORKFLOW_ENTINTY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FEATURE_COUNT = WORKFLOW_ENTINTY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.TaskImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getTask()
   * @generated
   */
  int TASK = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = WORKFLOW_ENTINTY__NAME;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PARAMS = WORKFLOW_ENTINTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = WORKFLOW_ENTINTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getParam()
   * @generated
   */
  int PARAM = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Param Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__PARAM_VALUE = 1;

  /**
   * The feature id for the '<em><b>Entity Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__ENTITY_VALUE = 2;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.FlowImpl <em>Flow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.FlowImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getFlow()
   * @generated
   */
  int FLOW = 6;

  /**
   * The feature id for the '<em><b>Sequence Start</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW__SEQUENCE_START = 0;

  /**
   * The feature id for the '<em><b>Sequence</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW__SEQUENCE = 1;

  /**
   * The number of structural features of the '<em>Flow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.NetworkImpl <em>Network</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.NetworkImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getNetwork()
   * @generated
   */
  int NETWORK = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK__NAME = WORKFLOW_ENTINTY__NAME;

  /**
   * The feature id for the '<em><b>Layers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK__LAYERS = WORKFLOW_ENTINTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Forwards</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK__FORWARDS = WORKFLOW_ENTINTY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Network</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK_FEATURE_COUNT = WORKFLOW_ENTINTY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.LayerImpl <em>Layer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.LayerImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getLayer()
   * @generated
   */
  int LAYER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__NAME = 0;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__OPTIONS = 1;

  /**
   * The number of structural features of the '<em>Layer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ForwardImpl <em>Forward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ForwardImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getForward()
   * @generated
   */
  int FORWARD = 9;

  /**
   * The feature id for the '<em><b>Sequence Start</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD__SEQUENCE_START = 0;

  /**
   * The feature id for the '<em><b>Sequence</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD__SEQUENCE = 1;

  /**
   * The number of structural features of the '<em>Forward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.FLOATImpl <em>FLOAT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.FLOATImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getFLOAT()
   * @generated
   */
  int FLOAT = 10;

  /**
   * The feature id for the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT__DEC = 0;

  /**
   * The feature id for the '<em><b>Per</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT__PER = 1;

  /**
   * The number of structural features of the '<em>FLOAT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.OptionImpl <em>Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.OptionImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getOption()
   * @generated
   */
  int OPTION = 11;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__TYPE = 0;

  /**
   * The feature id for the '<em><b>Input Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__INPUT_SIZE = 1;

  /**
   * The feature id for the '<em><b>Output Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__OUTPUT_SIZE = 2;

  /**
   * The feature id for the '<em><b>Dropeout Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__DROPEOUT_RATE = 3;

  /**
   * The number of structural features of the '<em>Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamValueImpl <em>Param Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamValueImpl
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getParamValue()
   * @generated
   */
  int PARAM_VALUE = 12;

  /**
   * The feature id for the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE__INT_VALUE = 0;

  /**
   * The feature id for the '<em><b>Float Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE__FLOAT_VALUE = 1;

  /**
   * The feature id for the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE__STRING_VALUE = 2;

  /**
   * The number of structural features of the '<em>Param Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.LayerType <em>Layer Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.extremexp.ssfhai.dsl.mLDSL.LayerType
   * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getLayerType()
   * @generated
   */
  int LAYER_TYPE = 13;


  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Model#getWorkflows <em>Workflows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Workflows</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Model#getWorkflows()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Workflows();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow <em>Workflow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Workflow</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Workflow
   * @generated
   */
  EClass getWorkflow();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getName()
   * @see #getWorkflow()
   * @generated
   */
  EAttribute getWorkflow_Name();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getTasks()
   * @see #getWorkflow()
   * @generated
   */
  EReference getWorkflow_Tasks();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getFlows <em>Flows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Flows</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getFlows()
   * @see #getWorkflow()
   * @generated
   */
  EReference getWorkflow_Flows();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getData()
   * @see #getWorkflow()
   * @generated
   */
  EReference getWorkflow_Data();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getNetworks <em>Networks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Networks</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getNetworks()
   * @see #getWorkflow()
   * @generated
   */
  EReference getWorkflow_Networks();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Data <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Data
   * @generated
   */
  EClass getData();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Data#getPath()
   * @see #getData()
   * @generated
   */
  EAttribute getData_Path();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Features</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Data#getFeatures()
   * @see #getData()
   * @generated
   */
  EAttribute getData_Features();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Data#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Data#getTarget()
   * @see #getData()
   * @generated
   */
  EAttribute getData_Target();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Task#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Task#getParams()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Params();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.WorkflowEntinty <em>Workflow Entinty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Workflow Entinty</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.WorkflowEntinty
   * @generated
   */
  EClass getWorkflowEntinty();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.WorkflowEntinty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.WorkflowEntinty#getName()
   * @see #getWorkflowEntinty()
   * @generated
   */
  EAttribute getWorkflowEntinty_Name();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Param#getName()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Name();

  /**
   * Returns the meta object for the containment reference '{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getParamValue <em>Param Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param Value</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Param#getParamValue()
   * @see #getParam()
   * @generated
   */
  EReference getParam_ParamValue();

  /**
   * Returns the meta object for the reference '{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getEntityValue <em>Entity Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity Value</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Param#getEntityValue()
   * @see #getParam()
   * @generated
   */
  EReference getParam_EntityValue();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Flow <em>Flow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flow</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Flow
   * @generated
   */
  EClass getFlow();

  /**
   * Returns the meta object for the reference '{@link eu.extremexp.ssfhai.dsl.mLDSL.Flow#getSequenceStart <em>Sequence Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sequence Start</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Flow#getSequenceStart()
   * @see #getFlow()
   * @generated
   */
  EReference getFlow_SequenceStart();

  /**
   * Returns the meta object for the reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Flow#getSequence <em>Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Sequence</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Flow#getSequence()
   * @see #getFlow()
   * @generated
   */
  EReference getFlow_Sequence();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Network <em>Network</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Network</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Network
   * @generated
   */
  EClass getNetwork();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Network#getLayers <em>Layers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Layers</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Network#getLayers()
   * @see #getNetwork()
   * @generated
   */
  EReference getNetwork_Layers();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Network#getForwards <em>Forwards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Forwards</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Network#getForwards()
   * @see #getNetwork()
   * @generated
   */
  EReference getNetwork_Forwards();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Layer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Layer
   * @generated
   */
  EClass getLayer();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Layer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Layer#getName()
   * @see #getLayer()
   * @generated
   */
  EAttribute getLayer_Name();

  /**
   * Returns the meta object for the containment reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Layer#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Layer#getOptions()
   * @see #getLayer()
   * @generated
   */
  EReference getLayer_Options();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Forward <em>Forward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forward</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Forward
   * @generated
   */
  EClass getForward();

  /**
   * Returns the meta object for the reference '{@link eu.extremexp.ssfhai.dsl.mLDSL.Forward#getSequenceStart <em>Sequence Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sequence Start</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Forward#getSequenceStart()
   * @see #getForward()
   * @generated
   */
  EReference getForward_SequenceStart();

  /**
   * Returns the meta object for the reference list '{@link eu.extremexp.ssfhai.dsl.mLDSL.Forward#getSequence <em>Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Sequence</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Forward#getSequence()
   * @see #getForward()
   * @generated
   */
  EReference getForward_Sequence();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.FLOAT <em>FLOAT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FLOAT</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.FLOAT
   * @generated
   */
  EClass getFLOAT();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getDec <em>Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dec</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getDec()
   * @see #getFLOAT()
   * @generated
   */
  EAttribute getFLOAT_Dec();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getPer <em>Per</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Per</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.FLOAT#getPer()
   * @see #getFLOAT()
   * @generated
   */
  EAttribute getFLOAT_Per();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Option
   * @generated
   */
  EClass getOption();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Option#getType()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_Type();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getInputSize <em>Input Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Input Size</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Option#getInputSize()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_InputSize();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getOutputSize <em>Output Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Output Size</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Option#getOutputSize()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_OutputSize();

  /**
   * Returns the meta object for the containment reference '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getDropeoutRate <em>Dropeout Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dropeout Rate</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.Option#getDropeoutRate()
   * @see #getOption()
   * @generated
   */
  EReference getOption_DropeoutRate();

  /**
   * Returns the meta object for class '{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue <em>Param Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Value</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.ParamValue
   * @generated
   */
  EClass getParamValue();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getIntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Value</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getIntValue()
   * @see #getParamValue()
   * @generated
   */
  EAttribute getParamValue_IntValue();

  /**
   * Returns the meta object for the containment reference '{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getFloatValue <em>Float Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Float Value</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getFloatValue()
   * @see #getParamValue()
   * @generated
   */
  EReference getParamValue_FloatValue();

  /**
   * Returns the meta object for the attribute '{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getStringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Value</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getStringValue()
   * @see #getParamValue()
   * @generated
   */
  EAttribute getParamValue_StringValue();

  /**
   * Returns the meta object for enum '{@link eu.extremexp.ssfhai.dsl.mLDSL.LayerType <em>Layer Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Layer Type</em>'.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.LayerType
   * @generated
   */
  EEnum getLayerType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MLDSLFactory getMLDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ModelImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Workflows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__WORKFLOWS = eINSTANCE.getModel_Workflows();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl <em>Workflow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getWorkflow()
     * @generated
     */
    EClass WORKFLOW = eINSTANCE.getWorkflow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKFLOW__NAME = eINSTANCE.getWorkflow_Name();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORKFLOW__TASKS = eINSTANCE.getWorkflow_Tasks();

    /**
     * The meta object literal for the '<em><b>Flows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORKFLOW__FLOWS = eINSTANCE.getWorkflow_Flows();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORKFLOW__DATA = eINSTANCE.getWorkflow_Data();

    /**
     * The meta object literal for the '<em><b>Networks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORKFLOW__NETWORKS = eINSTANCE.getWorkflow_Networks();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.DataImpl <em>Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.DataImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getData()
     * @generated
     */
    EClass DATA = eINSTANCE.getData();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA__PATH = eINSTANCE.getData_Path();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA__FEATURES = eINSTANCE.getData_Features();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA__TARGET = eINSTANCE.getData_Target();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.TaskImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__PARAMS = eINSTANCE.getTask_Params();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowEntintyImpl <em>Workflow Entinty</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.WorkflowEntintyImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getWorkflowEntinty()
     * @generated
     */
    EClass WORKFLOW_ENTINTY = eINSTANCE.getWorkflowEntinty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKFLOW_ENTINTY__NAME = eINSTANCE.getWorkflowEntinty_Name();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__NAME = eINSTANCE.getParam_Name();

    /**
     * The meta object literal for the '<em><b>Param Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM__PARAM_VALUE = eINSTANCE.getParam_ParamValue();

    /**
     * The meta object literal for the '<em><b>Entity Value</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM__ENTITY_VALUE = eINSTANCE.getParam_EntityValue();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.FlowImpl <em>Flow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.FlowImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getFlow()
     * @generated
     */
    EClass FLOW = eINSTANCE.getFlow();

    /**
     * The meta object literal for the '<em><b>Sequence Start</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOW__SEQUENCE_START = eINSTANCE.getFlow_SequenceStart();

    /**
     * The meta object literal for the '<em><b>Sequence</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOW__SEQUENCE = eINSTANCE.getFlow_Sequence();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.NetworkImpl <em>Network</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.NetworkImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getNetwork()
     * @generated
     */
    EClass NETWORK = eINSTANCE.getNetwork();

    /**
     * The meta object literal for the '<em><b>Layers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NETWORK__LAYERS = eINSTANCE.getNetwork_Layers();

    /**
     * The meta object literal for the '<em><b>Forwards</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NETWORK__FORWARDS = eINSTANCE.getNetwork_Forwards();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.LayerImpl <em>Layer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.LayerImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getLayer()
     * @generated
     */
    EClass LAYER = eINSTANCE.getLayer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER__NAME = eINSTANCE.getLayer_Name();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYER__OPTIONS = eINSTANCE.getLayer_Options();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ForwardImpl <em>Forward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ForwardImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getForward()
     * @generated
     */
    EClass FORWARD = eINSTANCE.getForward();

    /**
     * The meta object literal for the '<em><b>Sequence Start</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORWARD__SEQUENCE_START = eINSTANCE.getForward_SequenceStart();

    /**
     * The meta object literal for the '<em><b>Sequence</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORWARD__SEQUENCE = eINSTANCE.getForward_Sequence();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.FLOATImpl <em>FLOAT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.FLOATImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getFLOAT()
     * @generated
     */
    EClass FLOAT = eINSTANCE.getFLOAT();

    /**
     * The meta object literal for the '<em><b>Dec</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLOAT__DEC = eINSTANCE.getFLOAT_Dec();

    /**
     * The meta object literal for the '<em><b>Per</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLOAT__PER = eINSTANCE.getFLOAT_Per();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.OptionImpl <em>Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.OptionImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getOption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getOption();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__TYPE = eINSTANCE.getOption_Type();

    /**
     * The meta object literal for the '<em><b>Input Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__INPUT_SIZE = eINSTANCE.getOption_InputSize();

    /**
     * The meta object literal for the '<em><b>Output Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__OUTPUT_SIZE = eINSTANCE.getOption_OutputSize();

    /**
     * The meta object literal for the '<em><b>Dropeout Rate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTION__DROPEOUT_RATE = eINSTANCE.getOption_DropeoutRate();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamValueImpl <em>Param Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.ParamValueImpl
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getParamValue()
     * @generated
     */
    EClass PARAM_VALUE = eINSTANCE.getParamValue();

    /**
     * The meta object literal for the '<em><b>Int Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_VALUE__INT_VALUE = eINSTANCE.getParamValue_IntValue();

    /**
     * The meta object literal for the '<em><b>Float Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM_VALUE__FLOAT_VALUE = eINSTANCE.getParamValue_FloatValue();

    /**
     * The meta object literal for the '<em><b>String Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_VALUE__STRING_VALUE = eINSTANCE.getParamValue_StringValue();

    /**
     * The meta object literal for the '{@link eu.extremexp.ssfhai.dsl.mLDSL.LayerType <em>Layer Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.extremexp.ssfhai.dsl.mLDSL.LayerType
     * @see eu.extremexp.ssfhai.dsl.mLDSL.impl.MLDSLPackageImpl#getLayerType()
     * @generated
     */
    EEnum LAYER_TYPE = eINSTANCE.getLayerType();

  }

} //MLDSLPackage
