/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Model#getName <em>Name</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Model#getWorkflows <em>Workflows</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Workflows</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workflows</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getModel_Workflows()
   * @model containment="true"
   * @generated
   */
  EList<Workflow> getWorkflows();

} // Model
