/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Network</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Network#getLayers <em>Layers</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Network#getForwards <em>Forwards</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getNetwork()
 * @model
 * @generated
 */
public interface Network extends WorkflowEntinty
{
  /**
   * Returns the value of the '<em><b>Layers</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Layer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layers</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getNetwork_Layers()
   * @model containment="true"
   * @generated
   */
  EList<Layer> getLayers();

  /**
   * Returns the value of the '<em><b>Forwards</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Forward}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forwards</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getNetwork_Forwards()
   * @model containment="true"
   * @generated
   */
  EList<Forward> getForwards();

} // Network
