/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getType <em>Type</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getInputSize <em>Input Size</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getOutputSize <em>Output Size</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getDropeoutRate <em>Dropeout Rate</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getOption()
 * @model
 * @generated
 */
public interface Option extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link eu.extremexp.ssfhai.dsl.mLDSL.LayerType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.LayerType
   * @see #setType(LayerType)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getOption_Type()
   * @model
   * @generated
   */
  LayerType getType();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.LayerType
   * @see #getType()
   * @generated
   */
  void setType(LayerType value);

  /**
   * Returns the value of the '<em><b>Input Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Size</em>' attribute.
   * @see #setInputSize(int)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getOption_InputSize()
   * @model
   * @generated
   */
  int getInputSize();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getInputSize <em>Input Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Size</em>' attribute.
   * @see #getInputSize()
   * @generated
   */
  void setInputSize(int value);

  /**
   * Returns the value of the '<em><b>Output Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Size</em>' attribute.
   * @see #setOutputSize(int)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getOption_OutputSize()
   * @model
   * @generated
   */
  int getOutputSize();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getOutputSize <em>Output Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Size</em>' attribute.
   * @see #getOutputSize()
   * @generated
   */
  void setOutputSize(int value);

  /**
   * Returns the value of the '<em><b>Dropeout Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dropeout Rate</em>' containment reference.
   * @see #setDropeoutRate(FLOAT)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getOption_DropeoutRate()
   * @model containment="true"
   * @generated
   */
  FLOAT getDropeoutRate();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Option#getDropeoutRate <em>Dropeout Rate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dropeout Rate</em>' containment reference.
   * @see #getDropeoutRate()
   * @generated
   */
  void setDropeoutRate(FLOAT value);

} // Option
