/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getIntValue <em>Int Value</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getFloatValue <em>Float Value</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getStringValue <em>String Value</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParamValue()
 * @model
 * @generated
 */
public interface ParamValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Value</em>' attribute.
   * @see #setIntValue(int)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParamValue_IntValue()
   * @model
   * @generated
   */
  int getIntValue();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getIntValue <em>Int Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Value</em>' attribute.
   * @see #getIntValue()
   * @generated
   */
  void setIntValue(int value);

  /**
   * Returns the value of the '<em><b>Float Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float Value</em>' containment reference.
   * @see #setFloatValue(FLOAT)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParamValue_FloatValue()
   * @model containment="true"
   * @generated
   */
  FLOAT getFloatValue();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getFloatValue <em>Float Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float Value</em>' containment reference.
   * @see #getFloatValue()
   * @generated
   */
  void setFloatValue(FLOAT value);

  /**
   * Returns the value of the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Value</em>' attribute.
   * @see #setStringValue(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParamValue_StringValue()
   * @model
   * @generated
   */
  String getStringValue();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.ParamValue#getStringValue <em>String Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Value</em>' attribute.
   * @see #getStringValue()
   * @generated
   */
  void setStringValue(String value);

} // ParamValue
