/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getName <em>Name</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getParamValue <em>Param Value</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getEntityValue <em>Entity Value</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParam()
 * @model
 * @generated
 */
public interface Param extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParam_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Param Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Value</em>' containment reference.
   * @see #setParamValue(ParamValue)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParam_ParamValue()
   * @model containment="true"
   * @generated
   */
  ParamValue getParamValue();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getParamValue <em>Param Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Value</em>' containment reference.
   * @see #getParamValue()
   * @generated
   */
  void setParamValue(ParamValue value);

  /**
   * Returns the value of the '<em><b>Entity Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Value</em>' reference.
   * @see #setEntityValue(WorkflowEntinty)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getParam_EntityValue()
   * @model
   * @generated
   */
  WorkflowEntinty getEntityValue();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Param#getEntityValue <em>Entity Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Value</em>' reference.
   * @see #getEntityValue()
   * @generated
   */
  void setEntityValue(WorkflowEntinty value);

} // Param
