/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Task#getSource <em>Source</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Task#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends WorkflowEntinty
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getTask_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Task#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Param}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getTask_Params()
   * @model containment="true"
   * @generated
   */
  EList<Param> getParams();

} // Task
