/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl.mLDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getName <em>Name</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getTasks <em>Tasks</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getFlows <em>Flows</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getData <em>Data</em>}</li>
 *   <li>{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getNetworks <em>Networks</em>}</li>
 * </ul>
 *
 * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getWorkflow()
 * @model
 * @generated
 */
public interface Workflow extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getWorkflow_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link eu.extremexp.ssfhai.dsl.mLDSL.Workflow#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getWorkflow_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

  /**
   * Returns the value of the '<em><b>Flows</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Flow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flows</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getWorkflow_Flows()
   * @model containment="true"
   * @generated
   */
  EList<Flow> getFlows();

  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Data}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getWorkflow_Data()
   * @model containment="true"
   * @generated
   */
  EList<Data> getData();

  /**
   * Returns the value of the '<em><b>Networks</b></em>' containment reference list.
   * The list contents are of type {@link eu.extremexp.ssfhai.dsl.mLDSL.Network}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Networks</em>' containment reference list.
   * @see eu.extremexp.ssfhai.dsl.mLDSL.MLDSLPackage#getWorkflow_Networks()
   * @model containment="true"
   * @generated
   */
  EList<Network> getNetworks();

} // Workflow
