/*
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MLDSLStandaloneSetup extends MLDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MLDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
