/*
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MLDSLRuntimeModule extends AbstractMLDSLRuntimeModule {
}
