/**
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.ssfhai.dsl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MLDSLStandaloneSetup extends MLDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new MLDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
